
# DroneZone deprecated.
export PYTHONPATH=/vagrant/Maude4/Lib/python:/vagrant/DroneZone

export IOPBINDIR=${HOME}/bin/IOP

export MAUDE_LIB=/vagrant/Maude

export PATH=${IOPBINDIR}:${MAUDE_LIB}:${HOME}/jsbsim/src:${HOME}/ardupilot/Tools/autotest:/usr/lib/ccache:${PATH}

