#!/usr/bin/env python

import sys
import dronekit_sitl


usage = 'Usage:   {0} instanceno binary_path params_path home verbose'

def main(args):
    if len(args) != 6:
        print usage.format(args[0])
        return 1
    else:
        sitl = dronekit_sitl.SITL(instance=int(args[1]), path=args[2], defaults_filepath=args[3])
        largs = ['--home={0}'.format(args[4])]
        verbose = bool(args[5])
        sitl.launch(largs, verbose=verbose)
        sitl.block_until_ready(verbose=verbose)
        code = sitl.complete(verbose=verbose)
        sitl.poll()
        sitl.stop()
        # hpoefully should not see this...
        sys.stderr.write('\n----> SITL exiting <----\n')
        return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
