mod TEST is
 inc SCENARIO .
 inc ANALYSIS .
  inc SOLVE-SCP{valuation2valvisit} . 
 
 
var act : Action .
var kb : KB .

op ekb0 : -> KB .
ops acts : -> ActSet . 
ops lkb0 lkb1 ekb1  : -> KB .
op conf : -> Conf .

eq conf = 
[eI
  | clock(37)class(b(0),Bot)class(b(1),Bot)class(b(2),Bot)class(b(3),
    Bot)(timeElapsed(5.3065980000000003e+1)@ 37)(timeElapsed(
    5.3396006999999997e+1)@ 37)(timeElapsed(5.3745277000000002e+1)@ 37)(
    timeElapsed(5.4102936e+1)@ 37)(rand(0)@ 0)(atloc(b(0),pt(6,-2,-1))@ 37)(
    atloc(b(1),pt(96,100,0))@ 37)(atloc(b(2),pt(4,16,0))@ 37)(atloc(b(3),pt(
    108,129,0))@ 37)(energy(b(0),1.5e+1)@ 37)(energy(b(1),1.1e+1)@ 37)(energy(
    b(2),1.5e+1)@ 37)(energy(b(3),0.0)@ 37)(vel(b(0),1.83847763109e-1)@ 37)(
    vel(b(1),1.6155494421399999e-1)@ 37)(vel(b(2),1.3928388277199999e-1)@ 37)(
    vel(b(3),1.07703296143e-1)@ 37)(wind(1.0,0.0,0.0,536870912)@ 0)myHome(b(0),
    pt(0,0,0))myHome(b(1),pt(100,100,0))myHome(b(2),pt(10,10,0))myHome(b(3),pt(
    110,110,0))]
[b(0): Bot |
  lkb :(clock(37)class(b(0),Bot)(timeElapsed(5.1656531999999999e+1)@ 36)(rand(
    36)@ 36)(atloc(b(0),pt(6,-2,-1))@ 36)(pending(b(0),stop(b(0)))@ 37)(energy(
    b(0),1.5e+1)@ 36)(caution(b(0),2.0e+1)@ 0)(targetVel(b(0),5.0)@ 0)(vel(b(
    0),1.83847763109e-1)@ 36)(targets(b(0),pt(50,10,5); pt(10,30,5); pt(-20,50,
    5); pt(-40,5,5),nil)@ 0)(visitTimes(b(0),pt(10,30,5),6)@ 6)(visitTimes(b(
    0),pt(50,10,5),nil)@ 0)(visitTimes(b(0),pt(-20,50,5),13)@ 13)(visitTimes(b(
    0),pt(-40,5,5),23)@ 23)(eLoc(b(0),pt(0,0,0),31)@ 23)(eLoc(b(0),pt(10,30,5),
    8)@ 2)(eLoc(b(0),pt(-20,50,5),13)@ 6)(eLoc(b(0),pt(-40,5,5),23)@ 13)(wind(
    1.0,0.0,0.0,536870912)@ 0)myHome(b(0),pt(0,0,0))myAlt(b(0),5)),
  ckb :(class(b(0),Bot)atloc(b(0),pt(6,-2,-1))@ 36),
  evs :(tick @ 0)]
[b(1): Bot |
  lkb :(clock(37)class(b(1),Bot)(timeElapsed(5.1656531999999999e+1)@ 36)(rand(
    72)@ 36)(atloc(b(1),pt(96,100,0))@ 36)(pending(b(1),stop(b(1)))@ 37)(
    energy(b(1),1.1e+1)@ 36)(caution(b(1),2.0e+1)@ 0)(targetVel(b(1),5.0)@ 0)(
    vel(b(1),1.5231546211700001e-1)@ 36)(targets(b(1),pt(150,110,5); pt(110,
    130,5); pt(80,150,5); pt(60,105,5),nil)@ 0)(visitTimes(b(1),pt(60,105,5),
    23)@ 23)(visitTimes(b(1),pt(80,150,5),11)@ 11)(visitTimes(b(1),pt(110,130,
    5),6)@ 6)(visitTimes(b(1),pt(150,110,5),nil)@ 0)(eLoc(b(1),pt(60,105,5),
    21)@ 11)(eLoc(b(1),pt(80,150,5),13)@ 6)(eLoc(b(1),pt(100,100,0),31)@ 23)(
    eLoc(b(1),pt(110,130,5),8)@ 2)(wind(1.0,0.0,0.0,536870912)@ 0)myHome(b(1),
    pt(100,100,0))myAlt(b(1),5)),
  ckb :(class(b(1),Bot)atloc(b(1),pt(96,100,0))@ 36),
  evs :(tick @ 0)]
[b(2): Bot |
  lkb :(clock(37)class(b(2),Bot)(timeElapsed(5.1656531999999999e+1)@ 36)(rand(
    108)@ 36)(atloc(b(2),pt(4,16,0))@ 36)(pending(b(2),stop(b(2)))@ 37)(energy(
    b(2),1.5e+1)@ 36)(caution(b(2),2.0e+1)@ 0)(targetVel(b(2),5.0)@ 0)(vel(b(
    2),1.20830459736e-1)@ 36)(targets(b(2),pt(40,-10,10); pt(-40,-40,10); pt(
    -35,-5,10); pt(10,-30,10),nil)@ 0)(visitTimes(b(2),pt(10,-30,10),nil)@ 0)(
    visitTimes(b(2),pt(40,-10,10),23)@ 23)(visitTimes(b(2),pt(-35,-5,10),nil)@
    0)(visitTimes(b(2),pt(-40,-40,10),nil)@ 0)(eLoc(b(2),pt(10,10,0),31)@ 23)(
    eLoc(b(2),pt(40,-10,10),9)@ 2)(wind(1.0,0.0,0.0,536870912)@ 0)myHome(b(2),
    pt(10,10,0))myAlt(b(2),10)),
  ckb :(class(b(2),Bot)atloc(b(2),pt(4,16,0))@ 36),
  evs :(tick @ 0)]
[b(3): Bot |
  lkb :(clock(37)class(b(3),Bot)(timeElapsed(5.1656531999999999e+1)@ 36)(rand(
    144)@ 36)(atloc(b(3),pt(108,108,2))@ 36)(pending(b(3),stop(b(3)))@ 37)(
    energy(b(3),1.0)@ 36)(caution(b(3),2.0e+1)@ 0)(targetVel(b(3),5.0)@ 0)(vel(
    b(3),4.8301138702899998e-1)@ 36)(targets(b(3),pt(140,90,10); pt(60,60,10);
    pt(65,95,10); pt(110,70,10),nil)@ 0)(visitTimes(b(3),pt(60,60,10),26)@ 26)(
    visitTimes(b(3),pt(65,95,10),nil)@ 0)(visitTimes(b(3),pt(110,70,10),19)@
    19)(visitTimes(b(3),pt(140,90,10),7)@ 7)(eLoc(b(3),pt(60,60,10),29)@ 19)(
    eLoc(b(3),pt(110,70,10),14)@ 7)(eLoc(b(3),pt(110,110,0),40)@ 26)(eLoc(b(3),
    pt(140,90,10),9)@ 2)(wind(1.0,0.0,0.0,536870912)@ 0)myHome(b(3),pt(110,110,
    0))myAlt(b(3),10)),
  ckb :(class(b(3),Bot)atloc(b(3),pt(108,108,2))@ 36),
  evs :(tick @ 0)] .

eq acts = myActs(Bot,b(1),lkb1) .

ops getLKB0 getLKB1 : Conf -> KB .
op getEKB : Conf -> KB .
eq getLKB0([b(0) : Bot | lkb : kb, attrs:AttributeSet] conf:Conf) = kb .
eq getLKB1([b(1) : Bot | lkb : kb, attrs:AttributeSet] conf:Conf) = kb .
eq getEKB([eI | kb] conf:Conf) = kb .

 
eq lkb0 = getLKB0(conf) .
eq lkb1 = getLKB1(conf) .
eq ekb1 = getEKB(conf) .
                 
ops ev0 ev1 : -> Event .       
op evs0 : -> EventSet .           
ops lkb01 lkb02 lkb03 lkb04 lkb11 lkb12 lkb13 lkb14 : -> KB .
ops actKB01 actKB02 actKB11 actKB12 : -> ActionKB . 

eq lkb01 = getSensors(b(0),ekb1) .
eq lkb02 = proSensors(b(0),lkb0,lkb01) .

eq lkb11 = getSensors(b(1),ekb1) .
eq lkb12 = proSensors(b(1),lkb1,lkb11) .

eq actKB01 = act(b(0),lkb02) .
eq actKB11 = act(b(1),lkb12) .

eq lkb03 = getKB(actKB01) .
eq lkb13 = getKB(actKB11) .

eq actKB02 = doControl(getAct(actKB01),lkb03) .
eq actKB12 = doControl(getAct(actKB11),lkb13) .

op getKB : ActionKB -> KB .
eq getKB({act,kb}) = kb .

op getAct : ActionKB -> Action .
eq getAct({act,kb}) = act .


op pact : -> Action .
eq pact = getPending(b(0),lkb02) .

op loc : -> Loc .
eq loc = getLoc(b(0),lkb02) .


endm
***(

red doTask(Bot,b(1),tick,none,none,ekb0,lkb1) .

red notDone( takeOff(b(1), 10), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) .
false

Maude> red doTask(Bot,b(1),tick,none,none,ekb0,lkb1) .
reduce in TEST : doTask(Bot, b(1), tick, none, none, ekb0, lkb1) .
rewrites: 953 in 1ms cpu (1ms real) (689580 rewrites/second)
result KBEventsKB: {clock(3) class(b(1), Bot) (timeElapsed(3.0) @ 3) (rand(18)
    @ 3) (atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) @ 3) (pending(b(
    1), goToW(b(1), {senLoc(4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)}, 5.0)) @
    4) (countLate(b(1), 0) @ 0) (visited(b(1), nil) @ 0) (energy(b(1), 9.9e+1)
    @ 3) (caution(b(1), 2.0e+1) @ 0) (targetVel(b(1), 5.0) @ 0) (vel(b(1), 5.0)
    @ 0) (wind(0.0, 1.0, 0.0) @ 0) (targets(b(1), {senLoc(-4.0e+1, -4.0e+1,
    1.0e+1),pt(-40, -40, 10)} ; {senLoc(-3.5e+1, -5.0, 1.0e+1),pt(-35, -5, 10)}
    ; {senLoc(1.0e+1, -3.0e+1, 1.0e+1),pt(10, -30, 10)}, {senLoc(4.0e+1,
    -1.0e+1, 1.0e+1),pt(40, -10, 10)}) @ 4) (lastVisit(b(1), {senLoc(5.0, 0.0,
    0.0),pt(5, 0, 0)}, 0.0) @ 0) (countVisit(b(1), {senLoc(-4.0e+1, -4.0e+1,
    1.0e+1),pt(-40, -40, 10)}, 0) @ 0) (countVisit(b(1), {senLoc(-3.5e+1, -5.0,
    1.0e+1),pt(-35, -5, 10)}, 0) @ 0) (countVisit(b(1), {senLoc(1.0e+1,
    -3.0e+1, 1.0e+1),pt(10, -30, 10)}, 0) @ 0) (countVisit(b(1), {senLoc(
    4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)}, 0) @ 0) myHome(b(1), {senLoc(
    5.0, 0.0, 0.0),pt(5, 0, 0)}) myAlt(b(1), 10),
    (tick @ 1) goToW(b(1), 4.8076197382041155, -1.3736056394868901, 0.0, 0.0, 0.0, 0.0, 2.0) @ 0,
    class(b(1), Bot) atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) @ 3}
    
    
    )       
       
***(
{
[eI
	| clock(3) class(b(0), Bot) class(b(1), Bot) (timeElapsed(3.0) @ 3) (
    rand(12) @ 3) (atloc(b(0), {senLoc(9.8058067569092024, 1.9611613513818407,
    5.0),pt(10, 2, 5)}) @ 3) (atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0,
    10)}) @ 3) (energy(b(0), 9.9e+1) @ 3) (energy(b(1), 9.9e+1) @ 3) (vel(b(0),
    5.0) @ 0) (vel(b(1), 5.0) @ 0) wind(0.0, 1.0, 0.0) @ 0]
[b(0) : Bot |
  lkb : (clock(3) class(b(0), Bot) (timeElapsed(3.0) @ 3) (rand(15) @ 3) (
    atloc(b(0), {senLoc(9.8058067569092024, 1.9611613513818407, 5.0),pt(10, 2,
    5)}) @ 3) (pending(b(0), takeOff(b(0), 5)) @ 4) (countLate(b(0), 0) @ 0) (
    visited(b(0), nil) @ 0) (energy(b(0), 9.9e+1) @ 3) (caution(b(0), 2.0e+1) @
    0) (targetVel(b(0), 5.0) @ 0) (vel(b(0), 5.0) @ 0) (wind(0.0, 1.0, 0.0) @
    0) (targets(b(0), {senLoc(1.0e+1, 3.0e+1, 5.0),pt(10, 30, 5)} ; {senLoc(
    -2.0e+1, 5.0e+1, 5.0),pt(-20, 50, 5)} ; {senLoc(-4.0e+1, 5.0, 5.0),pt(-40,
    5, 5)}, {senLoc(5.0e+1, 1.0e+1, 5.0),pt(50, 10, 5)}) @ 2) (lastVisit(b(0),
    {senLoc(0.0, 0.0, 0.0),pt(0, 0, 0)}, 0.0) @ 0) (countVisit(b(0), {senLoc(
    -4.0e+1, 5.0, 5.0),pt(-40, 5, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(
    -2.0e+1, 5.0e+1, 5.0),pt(-20, 50, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(
    1.0e+1, 3.0e+1, 5.0),pt(10, 30, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(
    5.0e+1, 1.0e+1, 5.0),pt(50, 10, 5)}, 0) @ 0) myHome(b(0), {senLoc(0.0, 0.0,
    0.0),pt(0, 0, 0)}) myAlt(b(0), 5)),
  ckb : (class(b(0), Bot) atloc(b(0), {senLoc(9.8058067569092024,
    1.9611613513818407, 5.0),pt(10, 2, 5)}) @ 3),
  evs : ((tick @ 1) takeOff(b(0), 5) @ 0)]
[b(1) : Bot |
  lkb : (clock(3) class(b(1), Bot) (timeElapsed(2.0) @ 2) (rand(12) @ 2) (
    atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) @ 2) (pending(b(1),
    takeOff(b(1), 10)) @ 3) (countLate(b(1), 0) @ 0) (visited(b(1), nil) @ 0) (
    energy(b(1), 9.9e+1) @ 2) (caution(b(1), 2.0e+1) @ 0) (targetVel(b(1), 5.0)
    @ 0) (vel(b(1), 5.0) @ 0) (wind(0.0, 1.0, 0.0) @ 0) (targets(b(1), {senLoc(
    4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)} ; {senLoc(-4.0e+1, -4.0e+1,
    1.0e+1),pt(-40, -40, 10)} ; {senLoc(-3.5e+1, -5.0, 1.0e+1),pt(-35, -5, 10)}
    ; {senLoc(1.0e+1, -3.0e+1, 1.0e+1),pt(10, -30, 10)}, nil) @ 0) (lastVisit(
    b(1), {senLoc(5.0, 0.0, 0.0),pt(5, 0, 0)}, 0.0) @ 0) (countVisit(b(1), {
    senLoc(-4.0e+1, -4.0e+1, 1.0e+1),pt(-40, -40, 10)}, 0) @ 0) (countVisit(b(
    1), {senLoc(-3.5e+1, -5.0, 1.0e+1),pt(-35, -5, 10)}, 0) @ 0) (countVisit(b(
    1), {senLoc(1.0e+1, -3.0e+1, 1.0e+1),pt(10, -30, 10)}, 0) @ 0) (countVisit(
    b(1), {senLoc(4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)}, 0) @ 0) myHome(b(
    1), {senLoc(5.0, 0.0, 0.0),pt(5, 0, 0)}) myAlt(b(1), 10)),
  ckb : (class(b(1), Bot) atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)})
    @ 2),
  evs : (tick @ 0)]}
)