mod TEST is
 inc SCENARIO .
 
op ekb0 : -> KB .
ops acts : -> ActSet . 
ops lkb0 lkb1 ekb1  : -> KB .

eq acts = myActs(Bot,b(0),lkb1) .

eq lkb1 =   (clock(33) class(b(0), Bot) (timeElapsed(3.3e+1) @ 33) (rand(165) @ 33) (atloc(b(0), pt(-20,
    47, 5)) @ 33) (pending(b(0), goToW(b(0), pt(-20, 50, 5), 5.0)) @ 34) (countLate(b(0), 0) @ 0) (
    energy(b(0), 9.15e+1) @ 33) (caution(b(0), 8.5e+1) @ 0) (targetVel(b(0), 5.0) @ 0) (vel(b(0),
    5.0) @ 0) (wind(0.0, 1.0, 0.0) @ 0) (targets(b(0), pt(50, 10, 5) ; pt(10, 30, 5) ; pt(-20, 50, 5)
    ; pt(-40, 5, 5), nil) @ 0) (lastVisit(b(0), pt(0, 0, 0), 0.0) @ 0) (lastVisit(b(0), pt(10, 30,
    5), 7.0) @ 7) (lastVisit(b(0), pt(-20, 50, 5), 3.3e+1) @ 33) (countVisit(b(0), pt(10, 30, 5), 1)
    @ 7) (countVisit(b(0), pt(50, 10, 5), 0) @ 0) (countVisit(b(0), pt(-20, 50, 5), 19) @ 33) (
    countVisit(b(0), pt(-40, 5, 5), 0) @ 0) myHome(b(0), pt(0, 0, 0)) myAlt(b(0), 5)) .

eq ekb1 = clock(33) class(b(0), Bot) class(b(1), Bot) (timeElapsed(3.3e+1) @ 33) (rand(132) @ 33) (
    atloc(b(0), pt(-20, 47, 5)) @ 33) (atloc(b(1), pt(40, -10, 10)) @ 27) (energy(b(0), 9.15e+1) @
    33) (energy(b(1), 9.3e+1) @ 27) (vel(b(0), 5.0) @ 0) (vel(b(1), 5.0) @ 0) wind(0.0, 1.0, 0.0) @
    0 .
                 
ops ev0 ev1 : -> Event .
               
op evs0 : -> EventSet .           

ops ekb10 ekb11 : -> KB .

ops  lkb01 lkb02 lkb11 lkb12 : -> KB .
ops actKB : -> ActionKB . 

eq lkb01 = getSensors(b(1),ekb0) .
eq lkb02 = proSensors(b(1),lkb0,lkb01) .

eq lkb11 = getSensors(b(0),ekb1) .
eq lkb12 = proSensors(b(0),lkb1,lkb11) .
eq actKB = act(b(0),lkb12) .

op pact : -> Action .
eq pact = getPending(b(0),lkb02) .

op loc : -> Loc .
eq loc = getLoc(b(0),lkb02) .


endm
***(

red doTask(Bot,b(1),tick,none,none,ekb0,lkb1) .

red notDone( takeOff(b(1), 10), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) .
false

Maude> red doTask(Bot,b(1),tick,none,none,ekb0,lkb1) .
reduce in TEST : doTask(Bot, b(1), tick, none, none, ekb0, lkb1) .
rewrites: 953 in 1ms cpu (1ms real) (689580 rewrites/second)
result KBEventsKB: {clock(3) class(b(1), Bot) (timeElapsed(3.0) @ 3) (rand(18)
    @ 3) (atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) @ 3) (pending(b(
    1), goToW(b(1), {senLoc(4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)}, 5.0)) @
    4) (countLate(b(1), 0) @ 0) (visited(b(1), nil) @ 0) (energy(b(1), 9.9e+1)
    @ 3) (caution(b(1), 2.0e+1) @ 0) (targetVel(b(1), 5.0) @ 0) (vel(b(1), 5.0)
    @ 0) (wind(0.0, 1.0, 0.0) @ 0) (targets(b(1), {senLoc(-4.0e+1, -4.0e+1,
    1.0e+1),pt(-40, -40, 10)} ; {senLoc(-3.5e+1, -5.0, 1.0e+1),pt(-35, -5, 10)}
    ; {senLoc(1.0e+1, -3.0e+1, 1.0e+1),pt(10, -30, 10)}, {senLoc(4.0e+1,
    -1.0e+1, 1.0e+1),pt(40, -10, 10)}) @ 4) (lastVisit(b(1), {senLoc(5.0, 0.0,
    0.0),pt(5, 0, 0)}, 0.0) @ 0) (countVisit(b(1), {senLoc(-4.0e+1, -4.0e+1,
    1.0e+1),pt(-40, -40, 10)}, 0) @ 0) (countVisit(b(1), {senLoc(-3.5e+1, -5.0,
    1.0e+1),pt(-35, -5, 10)}, 0) @ 0) (countVisit(b(1), {senLoc(1.0e+1,
    -3.0e+1, 1.0e+1),pt(10, -30, 10)}, 0) @ 0) (countVisit(b(1), {senLoc(
    4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)}, 0) @ 0) myHome(b(1), {senLoc(
    5.0, 0.0, 0.0),pt(5, 0, 0)}) myAlt(b(1), 10),
    (tick @ 1) goToW(b(1), 4.8076197382041155, -1.3736056394868901, 0.0, 0.0, 0.0, 0.0, 2.0) @ 0,
    class(b(1), Bot) atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) @ 3}
    
    
    )       
       
***(
{
[eI
	| clock(3) class(b(0), Bot) class(b(1), Bot) (timeElapsed(3.0) @ 3) (
    rand(12) @ 3) (atloc(b(0), {senLoc(9.8058067569092024, 1.9611613513818407,
    5.0),pt(10, 2, 5)}) @ 3) (atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0,
    10)}) @ 3) (energy(b(0), 9.9e+1) @ 3) (energy(b(1), 9.9e+1) @ 3) (vel(b(0),
    5.0) @ 0) (vel(b(1), 5.0) @ 0) wind(0.0, 1.0, 0.0) @ 0]
[b(0) : Bot |
  lkb : (clock(3) class(b(0), Bot) (timeElapsed(3.0) @ 3) (rand(15) @ 3) (
    atloc(b(0), {senLoc(9.8058067569092024, 1.9611613513818407, 5.0),pt(10, 2,
    5)}) @ 3) (pending(b(0), takeOff(b(0), 5)) @ 4) (countLate(b(0), 0) @ 0) (
    visited(b(0), nil) @ 0) (energy(b(0), 9.9e+1) @ 3) (caution(b(0), 2.0e+1) @
    0) (targetVel(b(0), 5.0) @ 0) (vel(b(0), 5.0) @ 0) (wind(0.0, 1.0, 0.0) @
    0) (targets(b(0), {senLoc(1.0e+1, 3.0e+1, 5.0),pt(10, 30, 5)} ; {senLoc(
    -2.0e+1, 5.0e+1, 5.0),pt(-20, 50, 5)} ; {senLoc(-4.0e+1, 5.0, 5.0),pt(-40,
    5, 5)}, {senLoc(5.0e+1, 1.0e+1, 5.0),pt(50, 10, 5)}) @ 2) (lastVisit(b(0),
    {senLoc(0.0, 0.0, 0.0),pt(0, 0, 0)}, 0.0) @ 0) (countVisit(b(0), {senLoc(
    -4.0e+1, 5.0, 5.0),pt(-40, 5, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(
    -2.0e+1, 5.0e+1, 5.0),pt(-20, 50, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(
    1.0e+1, 3.0e+1, 5.0),pt(10, 30, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(
    5.0e+1, 1.0e+1, 5.0),pt(50, 10, 5)}, 0) @ 0) myHome(b(0), {senLoc(0.0, 0.0,
    0.0),pt(0, 0, 0)}) myAlt(b(0), 5)),
  ckb : (class(b(0), Bot) atloc(b(0), {senLoc(9.8058067569092024,
    1.9611613513818407, 5.0),pt(10, 2, 5)}) @ 3),
  evs : ((tick @ 1) takeOff(b(0), 5) @ 0)]
[b(1) : Bot |
  lkb : (clock(3) class(b(1), Bot) (timeElapsed(2.0) @ 2) (rand(12) @ 2) (
    atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)}) @ 2) (pending(b(1),
    takeOff(b(1), 10)) @ 3) (countLate(b(1), 0) @ 0) (visited(b(1), nil) @ 0) (
    energy(b(1), 9.9e+1) @ 2) (caution(b(1), 2.0e+1) @ 0) (targetVel(b(1), 5.0)
    @ 0) (vel(b(1), 5.0) @ 0) (wind(0.0, 1.0, 0.0) @ 0) (targets(b(1), {senLoc(
    4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)} ; {senLoc(-4.0e+1, -4.0e+1,
    1.0e+1),pt(-40, -40, 10)} ; {senLoc(-3.5e+1, -5.0, 1.0e+1),pt(-35, -5, 10)}
    ; {senLoc(1.0e+1, -3.0e+1, 1.0e+1),pt(10, -30, 10)}, nil) @ 0) (lastVisit(
    b(1), {senLoc(5.0, 0.0, 0.0),pt(5, 0, 0)}, 0.0) @ 0) (countVisit(b(1), {
    senLoc(-4.0e+1, -4.0e+1, 1.0e+1),pt(-40, -40, 10)}, 0) @ 0) (countVisit(b(
    1), {senLoc(-3.5e+1, -5.0, 1.0e+1),pt(-35, -5, 10)}, 0) @ 0) (countVisit(b(
    1), {senLoc(1.0e+1, -3.0e+1, 1.0e+1),pt(10, -30, 10)}, 0) @ 0) (countVisit(
    b(1), {senLoc(4.0e+1, -1.0e+1, 1.0e+1),pt(40, -10, 10)}, 0) @ 0) myHome(b(
    1), {senLoc(5.0, 0.0, 0.0),pt(5, 0, 0)}) myAlt(b(1), 10)),
  ckb : (class(b(1), Bot) atloc(b(1), {senLoc(5.0, 0.0, 1.0e+1),pt(5, 0, 10)})
    @ 2),
  evs : (tick @ 0)]}
)