**** load load 

load load-maude
load sitl

load model-checker 
load /home/vagrant/imaude/ilib/load-lib
load ../../Lib/meta-cp-e 
loop init .

(seq
 (pyexe plambda (load "../../Lib/drone.lsp"))
 (pyexe plambda (define b0 (apply mkdrone "b0" (int 0) (boolean false) 
                                          (boolean false) "log.txt" )))
 --- (pyexe plambda (define b1 (apply mkdrone "b1" (int 1))))
 (pyexe plambda (apply setStartTime))
 (initAgentEset maude g2d g2d plambda SITL asys2 Drone) 
)
