mod TEST is
  inc SCENARIO .
  inc MODEL-TASKS .

vars id : Id .
  var cl : Class .
  vars  t t0 t1 t2 t3 t4 t5 t6 : Time .
  vars l loc loc0 home locR loc1 loc2 : Loc .
  vars senl0 senl1 senlR senlD : SenLoc .
  vars gl0 gl1 : GridLoc .
  vars kb kb0 kbp kb1 : KB .
  vars evs evs' ievs devs : EventSet . 
  var dir dir1 : Dir .
  var act act0 act1  : Action .
  vars acts acts0 pact : ActSet .
  var e v c x y z sx sy sz sx0 sy0 sz0 sx1 sy1 sz1 sx2 sy2 sz2 sx3 sy3 sz3 : FiniteFloat .
  vars alt ix iy iz ix0 iy0 iz0 : Int .
  var r j n : Nat .
  
  vars locs locs0 locs1 locs2 locs3 : LocList .

  ops lkb ekb lkb0 ekb0 lkb1 lkb2 : -> KB .
  op conf0 : -> Conf .
  op gotos : -> ActSet .
  op sSCP : KB -> ActSet .
  op evalIf : KB -> KB .

 
 eq lkb0 = getLKB(b(0),conf1) .
 eq ekb0 = clock(0) class(b(0), Bot) (rand(0) @ 0) (atloc(b(0), {senLoc(0.0, 0.0, 0.0),pt(0, 0, 0)}) @ 0) (energy(b(0),
    1.0e+2) @ 0) targetVel(b(0), 5.0) @ 0 .

  eq lkb = (clock(0) class(b(0), Bot) (rand(0) @ 0) (atloc(b(0), {senLoc(0.0, 0.0, 0.0),pt(0, 0, 0)}) @ 0) (visited(b(0), nil)
    @ 0) (energy(b(0), 1.0e+2) @ 0) (caution(b(0), 7.0e+1) @ 0) (targetVel(b(0), 5.0) @ 0) (targets(b(0), {senLoc(5.0e+1,
    -5.0e+1, 5.0),pt(50, -50, 5)} ; {senLoc(5.0e+1, 5.0e+1, 5.0),pt(50, 50, 5)} ; {senLoc(-5.0e+1, 5.0e+1, 5.0),pt(-50, 50,
    5)} ; {senLoc(-5.0e+1, -5.0e+1, 5.0),pt(-50, -50, 5)}, nil) @ 0) (lastVisit(b(0), {senLoc(0.0, 0.0, 0.0),pt(0, 0, 0)},
    0.0) @ 0) (countVisit(b(0), {senLoc(-5.0e+1, -5.0e+1, 5.0),pt(-50, -50, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(-5.0e+1,
    5.0e+1, 5.0),pt(-50, 50, 5)}, 0) @ 0) (countVisit(b(0), {senLoc(5.0e+1, -5.0e+1, 5.0),pt(50, -50, 5)}, 0) @ 0) (
    countVisit(b(0), {senLoc(5.0e+1, 5.0e+1, 5.0),pt(50, 50, 5)}, 0) @ 0) myHome(b(0), {senLoc(0.0, 0.0, 0.0),pt(0, 0, 0)})
    myAlt(b(0), 5)) .

 
endm
